package com.assignment;

import static springfox.documentation.builders.PathSelectors.any;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;

import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@SpringBootApplication
@ComponentScan()
@EnableSwagger2
public class Run extends SpringBootServletInitializer{

	    public static void main(String[] args) {
	        SpringApplication.run(Run.class, args);
	    }
	    
		@Bean
		public Docket docket() {
			return new Docket(DocumentationType.SWAGGER_2).select()
					.apis(RequestHandlerSelectors.basePackage(getClass().getPackage().getName()))
					.paths(any())
					.build()
					.apiInfo(generateApiInfo());
		}

		private ApiInfo generateApiInfo() {
			return new ApiInfo("Cell phone number assigning app",
					"This service is to assign the autogenerated number and assign user specific number to the service",
					"Version 1.0",
					"urn:tos",
					"tfrancis@scu.edu",
					"Apache 2.0",
					"http://www.apache.org/licenses/LICENSE-2.0");
		}
		
}
